services:
  mysql:
    image: mysql:5
    environment:
     - MYSQL_DATABASE=${DB_NAME}
     - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
    ports:
      - '3306:3306'
    volumes:
      - ./mysql_data:/var/lib/mysql
